env:
  browser: true
  commonjs: true
  es6: true
  node: true
parserOptions:
  ecmaVersion: 2017
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console: 1
  no-empty: 1
